/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tool_sysinfo_linux_disk_SyncDiskInfoJNI */

#ifndef _Included_tool_sysinfo_linux_disk_SyncDiskInfoJNI
#define _Included_tool_sysinfo_linux_disk_SyncDiskInfoJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tool_sysinfo_linux_disk_SyncDiskInfoJNI
 * Method:    syncDiskInfo
 * Signature: (Ljava/lang/String;[J)V
 */
JNIEXPORT void JNICALL Java_tool_sysinfo_linux_disk_SyncDiskInfoJNI_syncDiskInfo
  (JNIEnv *, jobject, jstring, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
